### ISSUE TITLE
"Unexpected error occurred" on all commands

### ISSUE THREAD

**Issue by lukewalz** [arbs-io/vscode-openai-docs#5]
"unexpected error occured: undefined, Please help and report issue to github issue. Providing operation and configuration setup (excluding any sensitive data)"

This appears on both he general chat and also all commands. Configured with API key successfully from https://platform.openai.com/account/api-keys

**Comment by arbs-io** [comment]
Hi @lukewalz 
Sorry to hear that you're having issues. I've checked both azure and openai and I can't see any issues. Could you confirm the setting for the vscode-openai extension. Is the service provider set to OpenAI?

**Comment by arbs-io** [comment]
I've added an error stack to capture more info (v1.0.16). Could you remove the sensitive data and post the results here? I very much appreciate you taking the time to help report issues.

**Comment by lukewalz** [comment]
Is this what you need?

**Comment by arbs-io** [comment]
> 

Was there an attachment with the JSON file? i don't think it came through via email

**Comment by lukewalz** [comment]
<img width="848" alt="Screenshot 2023-04-06 at 10 36 13 PM" src="https://user-images.githubusercontent.com/25109068/230640145-18adeb69-61a3-47d5-b432-a2798a27cfa3.png">

**Comment by arbs-io** [comment]
Perfect thanks. The setup looks good. Are you still receiving an error? You should see an error message (toaster message box). It will contain a stack trace with more information. Could you provide json here (remove you api key from the content)

**Comment by lukewalz** [comment]
<img width="454" alt="Screenshot 2023-04-08 at 2 28 55 PM" src="https://user-images.githubusercontent.com/25109068/230739418-bb51d00f-6d06-4a8d-aab1-8a7a57ed9b1a.png">

This is all I am getting

**Comment by arbs-io** [comment]
Could you upgrade the version. The latest version should provide a stack trace of issues. Which will help me identify where the issue has occurred

**Comment by lukewalz** [comment]
<img width="467" alt="Screenshot 2023-04-10 at 9 38 32 AM" src="https://user-images.githubusercontent.com/25109068/230923698-50ae38a4-b3d3-4a2e-a571-a40e729c88a7.png">

**Comment by arbs-io** [comment]
Great, thank you!

It appears that you may have exceeded your current quota with OpenAI, resulting in a 429 response. Not to worry though, we can help you resolve this issue by referring you to this link: https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details

Have you been using a free account and possibly used up all of your free credits? Unfortunately, as this issue is coming from the vendor (OpenAI), I won't be able to fix it myself. However, I'm happy to assist in any way possible.

On a positive note, I'm excited to announce that we're currently working on adding a preview feature that will provide a free chat instance soon (most likely next week). We're taking extra precautions and working through the security model to ensure its safety. Please check back soon as we anticipate it should work seamlessly out of the box!
